version: '3.8'

services:
  web:
    build: .
    ports:
      - "8080:80"
    volumes:
      - .:/var/www/html
    depends_on:
      - db

  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: ignite2
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    volumes:
      - ./Base de datos/ignite2.sql:/docker-entrypoint-initdb.d/ignite2.sql

volumes:
  db_data: